name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build shared-result package
        run: yarn workspace shared-result build

      - name: Refresh package links
        run: yarn install --force

      - name: Verify shared-result package
        run: |
          echo "Checking shared-result dist files:"
          ls -la packages/result/dist/ || echo "No dist directory"
          echo "Checking backend symlink:"
          ls -la backend/node_modules/shared-result/dist/ || echo "No backend symlink dist"
          echo "Testing package resolution:"
          (cd backend && node -e "console.log('shared-result resolved to:', require.resolve('shared-result'))") || echo "Resolution failed"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build applications
        run: yarn build

      - name: Run Playwright tests
        run: yarn test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30