name: Lint & Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: Run Linting and Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build shared-result package
        run: yarn workspace shared-result build

      - name: Refresh package links
        run: yarn install --force

      - name: Debug package installation
        run: |
          echo "=== Checking shared-result package installation ==="
          echo "Root node_modules:"
          ls -la node_modules/ | grep shared || echo "shared-result not found in root node_modules"
          echo "Backend node_modules:"
          ls -la backend/node_modules/ | grep shared || echo "shared-result not found in backend/node_modules"
          echo "Frontend node_modules:"
          ls -la frontend/node_modules/ | grep shared || echo "shared-result not found in frontend/node_modules"
          echo "Packages result contents:"
          ls -la packages/result/
          echo "Packages result dist contents:"
          ls -la packages/result/dist/ || echo "dist directory not found"
          echo "Checking yarn workspaces:"
          yarn workspaces info
          echo "Testing ESM import resolution:"
          node --input-type=module -e "import('shared-result').then(() => console.log('ESM import works')).catch(e => console.log('ESM import failed:', e.message))"
          echo "Package build status:"
          cat packages/result/package.json | grep -A 5 '"scripts"'

      - name: Run linting
        run: yarn lint

      - name: Run type checking
        run: yarn typecheck