name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build result package
        run: yarn workspace result build

      - name: Refresh package links
        run: yarn install --force

      - name: Run backend unit tests
        run: yarn workspace backend test

      - name: Run frontend unit tests
        run: yarn workspace frontend test